ALTER DATABASE foodtaxidb CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE TH_BID COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE TH_DELIVERY COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_BID COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_BRAND COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_CLIENT COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_DELIVERY COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_DELIVERY_PAYMENT COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_DRIVER COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_INVOICE COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_ORDER COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_ORDER_PAYMENT COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_SHOP COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;
ALTER TABLE T_SHOP_USER COLLATE='utf8mb4_unicode_ci', CONVERT TO CHARSET utf8mb4;